/**
 * ============================================================================
 * PLACEHOLDER DEVELOPMENT CONTENT — NOT CLIENT COPY. DO NOT SHIP.
 * ============================================================================
 *
 * Four Nepal trekking regions, so the region pages have something to render
 * while the admin is being built.
 *
 * **The geography is real; the prose is not client copy.** Region names,
 * locations, permit situations and season windows are ordinary verifiable
 * facts about Nepal. Every `description` nonetheless opens with an explicit
 * PLACEHOLDER marker, because it was written here rather than supplied by Trek
 * & Climb Adventure — the same treatment the FAQ answers and the About page
 * team records get, and for the same reason: an unmarked paragraph on a public
 * page is indistinguishable from approved copy the moment this session ends.
 *
 * Cover images point at `treknclimb/regions/<slug>`, following the prefixing
 * convention. **Nothing has been uploaded to those IDs.** `CloudinaryImage`
 * falls back to a labelled placeholder block rather than a broken image, so
 * the pages render — but they are not illustrated until someone uploads four
 * files.
 *
 *   npx tsx --env-file=.env.local scripts/seed-regions.ts
 *   npx tsx --env-file=.env.local scripts/seed-regions.ts --force
 *   npx tsx --env-file=.env.local scripts/seed-regions.ts --remove
 *
 * **Written and saved as UTF-8.** Every en dash and curly apostrophe below is
 * a real character, not an escape. Do not edit this file with PowerShell's
 * `Set-Content` or `Out-File` without `-Encoding utf8`: they default to the
 * system ANSI codepage, which is what put U+FFFD into twelve stored fields
 * once already. See `models/shared/noMojibake.ts`.
 */

import mongoose from 'mongoose';

import { connectDB } from '../lib/db';
import Destination from '../models/Destination';
import Region, { IRegion } from '../models/Region';
import Trip from '../models/Trip';

const MARKER = 'PLACEHOLDER COPY, NOT CLIENT-APPROVED —';

type RegionSeed = Omit<
  IRegion,
  '_id' | 'createdAt' | 'updatedAt' | 'slugHistory' | 'noIndex' | 'destination'
> & { destinationSlug: string };

const regions: RegionSeed[] = [
  {
    name: 'Annapurna',
    slug: 'annapurna',
    destinationSlug: 'nepal',
    displayOrder: 1,
    description: `${MARKER} the Annapurna region begins an hour north of Pokhara, which makes it the most reachable of Nepal's trekking areas and the usual choice for a first Himalayan trek. Routes range from three-day walks between lodges at 2,000 m to the three-week circuit over the Thorong La at 5,416 m. Teahouses are close together and comfortable, so nothing here needs a tent or a support crew.`,
    coverImage: 'treknclimb/regions/annapurna',
    coverImageAlt:
      'Machhapuchhre and the Annapurna range at dawn, seen across terraced foothills',
  },
  {
    name: 'Everest',
    slug: 'everest',
    destinationSlug: 'nepal',
    displayOrder: 2,
    description: `${MARKER} the Everest region, or Khumbu, is reached by a short mountain flight to Lukla rather than by road, and that flight is the part of the trip most likely to move — it is weather-dependent and cancellations are normal in cloud. Trails run high, with most itineraries spending several nights above 4,000 m, so the schedules here are built around acclimatisation days rather than distance.`,
    coverImage: 'treknclimb/regions/everest',
    coverImageAlt:
      'Ama Dablam rising above the Khumbu valley with prayer flags in the foreground',
  },
  {
    name: 'Langtang',
    slug: 'langtang',
    destinationSlug: 'nepal',
    displayOrder: 3,
    description: `${MARKER} Langtang is the closest trekking region to Kathmandu, reached in a day by road with no internal flight involved. It carries far fewer walkers than Annapurna or Everest, which is the main reason to choose it. The valley was severely damaged in the 2015 earthquake and has been rebuilt by the communities living in it; lodges are open along the length of the route.`,
    coverImage: 'treknclimb/regions/langtang',
    coverImageAlt:
      'The Langtang valley under snow with a stone lodge on the trail',
  },
  {
    name: 'Manaslu',
    slug: 'manaslu',
    destinationSlug: 'nepal',
    displayOrder: 4,
    description: `${MARKER} Manaslu is a restricted area. Trekking it requires a special permit issued through a registered agency, a minimum party of two, and a licensed guide throughout — it cannot be walked independently. The permit takes time to obtain, so this is the region that needs the most notice: plan on several weeks between the inquiry and the start date rather than several days.`,
    coverImage: 'treknclimb/regions/manaslu',
    coverImageAlt:
      'Manaslu north face above the Budhi Gandaki valley on a clear morning',
  },
];

async function run(): Promise<void> {
  const force = process.argv.includes('--force');
  const remove = process.argv.includes('--remove');

  await connectDB();

  const slugs = regions.map((region) => region.slug);

  if (remove) {
    /*
     * Trips referencing a region being deleted would be left pointing at an
     * ObjectId with nothing behind it. Cleared first, in that order: a dangling
     * ref is worse than a null one, and doing it the other way round leaves a
     * window where both are true.
     */
    const owned = await Region.find({ slug: { $in: slugs } })
      .select('_id')
      .lean<{ _id: mongoose.Types.ObjectId }[]>();

    const cleared = await Trip.updateMany(
      { region: { $in: owned.map((r) => r._id) } },
      { $set: { region: null } }
    );

    const deleted = await Region.deleteMany({ slug: { $in: slugs } });

    console.log(`Cleared the region on ${cleared.modifiedCount} trip(s).`);
    console.log(`Removed ${deleted.deletedCount} placeholder region(s).`);

    await mongoose.disconnect();
    return;
  }

  const existing = await Region.countDocuments();

  if (existing > 0 && !force) {
    console.log(
      `${existing} regions already exist. This script only creates placeholder ` +
        'development data, so it will not overwrite anything. Re-run with --force to replace them.'
    );
    await mongoose.disconnect();
    return;
  }

  if (force) {
    /*
     * `--force` deletes and recreates, which means new ObjectIds — so every
     * trip pointing at an old region would be orphaned. CLAUDE.md forbids
     * `seed.ts --force` for exactly this reason. Here the refs are re-resolved
     * by slug afterwards, so the relationship survives the new ids.
     */
    const before = await Trip.find({ region: { $ne: null } })
      .select('_id slug region')
      .populate('region', 'slug')
      .lean<{ _id: mongoose.Types.ObjectId; slug: string; region: { slug: string } | null }[]>();

    const previous = new Map(
      before
        .filter((trip) => trip.region)
        .map((trip) => [String(trip._id), trip.region!.slug])
    );

    await Region.deleteMany({});
    console.log('Cleared existing regions.');

    await writeRegions();

    const bySlug = new Map(
      (await Region.find().select('_id slug').lean<{ _id: mongoose.Types.ObjectId; slug: string }[]>()).map(
        (region) => [region.slug, region._id]
      )
    );

    let relinked = 0;

    for (const [tripId, regionSlug] of previous) {
      const id = bySlug.get(regionSlug);
      if (!id) continue;

      await Trip.updateOne({ _id: tripId }, { $set: { region: id } });
      relinked += 1;
    }

    console.log(`Re-linked ${relinked} trip(s) to their region by slug.`);

    await mongoose.disconnect();
    console.log('Done. This is placeholder content — replace it before launch.');
    return;
  }

  await writeRegions();

  await mongoose.disconnect();
  console.log('Done. This is placeholder content — replace it before launch.');
}

async function writeRegions(): Promise<void> {
  const destinations = await Destination.find()
    .select('_id slug name')
    .lean<{ _id: mongoose.Types.ObjectId; slug: string; name: string }[]>();

  const bySlug = new Map(destinations.map((d) => [d.slug, d]));

  const documents = regions.map(({ destinationSlug, ...region }) => {
    const destination = bySlug.get(destinationSlug);

    if (!destination) {
      throw new Error(
        `Destination "${destinationSlug}" not found — run scripts/seed.ts first.`
      );
    }

    return { ...region, destination: destination._id };
  });

  /*
   * `insertMany` runs validation, so the reserved-slug rule and the U+FFFD
   * guard both fire here. A region whose description picked up a replacement
   * character on its way into this file fails loudly rather than shipping.
   */
  const inserted = await Region.insertMany(documents);

  console.log(`Inserted ${inserted.length} placeholder regions:`);
  for (const region of inserted) console.log(`  ${region.name} (${region.slug})`);
}

run().catch(async (error) => {
  console.error('Region seed failed:', error);
  await mongoose.disconnect();
  process.exit(1);
});
